app/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.contrib import admin
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static
from django.shortcuts import render, get_object_or_404
from django.views.static import serve
from app import views as apviews




urlpatterns = [    
    # path('', apviews.home, name='store_home'),
    path('store/<str:slug>/', apviews.storehome, name='store_home'),    
    path('', apviews.home, name='customer_home'),
    path('store/products/<str:slug>', apviews.storeproducts, name='customer_store_products'),

    path('slideshows', apviews.slideshows, name='customer_slideshows'),
    path('top_categories', apviews.topcategories, name='customer_top_categories'),
    path('order/<str:orderid>', apviews.myorder, name='customer_my_order'),
    path('download_order/<str:orderid>', apviews.downloadorder, name='customer_download_order'),
    path('remove_order/<str:id>', apviews.remove_order, name='customer_remove_order'),
    # path('checkout', apviews.checkout, name='customer_checkout'),
    path('error_500', apviews.error500page, name='customer_error_500'),
    path('error_404', apviews.error404page, name='customer_error_404'),
    path('carted_product/<str:id>', apviews.cartedproduct, name='customer_carted_product'),
    path('new_products', apviews.newproducts, name='customer_new_products'),
    path('pay_on_delivery/<str:orderid>', apviews.payondelivery, name='customer_pay_on_delivery'),
    path('remove_from_cart/<str:id>', apviews.remove_from_cart, name='customer_remove_carted_product'),
    path('home_group/<str:id>', apviews.homegroupproducts, name='customer_home_group_products'),
    path('flashsale/all/products/<str:id>', apviews.allflashsaleproducts, name='all_customer_flash_sales_products'),
    path('flash_sales_products/<str:id>', apviews.flashsaleproducts, name='customer_flash_sales_products'),
    path('flashsale/', apviews.flashsalespage, name='customer_flash_sales_page'),
    path('brand/<str:slug>', apviews.brandpage, name='customer_brand_page'),
    path('brand/products/<str:slug>', apviews.brandproducts, name='customer_brand_products'),
    path('slide/<str:slug>', apviews.slideshowpage, name='customer_slideshow_page'),
    path('slideshow/products/<str:slug>', apviews.slideshowproducts, name='customer_slideshow_products'),
    path('flash_sales_product/<str:id>', apviews.flashsaleproduct, name='customer_flash_sales_product'),
    path('product/<str:id>', apviews.product, name='customer_product'),
    path('product_details/<str:productid>', apviews.product_details, name='customer_product_details'),
    path('add_to_cart/<str:productid>', apviews.add_to_cart, name='customer_add_to_cart'),
    path('add_variation_to_cart/', apviews.add_variation_to_cart, name='customer_add_variation_to_cart'),
    path('similiar_products/<str:productid>', apviews.similarproducts, name='customer_similar_products'),
    path('add_to_saved/<str:productid>', apviews.add_to_saved, name='customer_add_to_saved'),
    path('remove_from_saved/<str:productid>', apviews.remove_from_saved, name='customer_remove_from_saved'),
    path('category/<str:name>', apviews.categorys, name='customer_our_offers'),
    path('offer_products/<str:name>', apviews.categoryproducts, name='customer_offer_products'),
    path('category/<str:name>', apviews.categorys, name='customer_our_categorys'),
    path('group/<str:slug>', apviews.homegroup, name='customer_home_group'),
    path('group/products/<str:slug>', apviews.allhomegroupproducts, name='all_customer_home_group_products'),
    path('group/all/', apviews.allhomegroupsection, name='all_customer_home_group_sections'),
    path('newsletter/subscribe/', apviews.newlettersubscription, name='customer_news_letter_subscription'),
    path('brand/<str:name>', apviews.categorys, name='customer_brands'),
    path('category_products/<str:name>', apviews.categoryproducts, name='customer_category_products'),
    path('update_cart/', apviews.update_cart, name='customer_update_cart'),
    path('cart_count/', apviews.cart_count, name='customer_cart_count'),
    path('products/all', apviews.allproducts, name='customer_all_products'),
    path('products/page/all', apviews.allproductspage, name='customer_all_products_page'),
    path('products/paginated', apviews.paginatedproducts, name='customer_paginated_products'),
    path('products_you_may_like/', apviews.products_you_may_like, name='customer_products_you_may_like'),
    path('saved_items/', apviews.saveditemspage, name='customer_saved_items_page'),
    path('saved_items/products', apviews.savedproducts, name='customer_saved_items_products'),
    path('search/', apviews.search_products, name='customer_search_products'),
    path('place_order/', apviews.place_order, name='customer_place_order'),
    path('my_orders/', apviews.myorders, name='customer_my_orders'),

    path('cart/', apviews.cartpage, name='customer_cart_page'),
    path('customer/cart/', apviews.cart, name='customer_cart'),
    path('update_contact_details/', apviews.updatecontactdetails, name='customer_update_contact_details'),
    path('order_paid', apviews.orderpaid, name='customer_order_paid'),
    path('verify_payment', apviews.verifypayment, name='customer_verify_payment'),
     path("customer/signup/",apviews.customersignup,name='customer_signup'),
      url("customer/auth/", apviews.loginuser, name='customer_auth'),
    # #   url("customer/new/accounts/signup/", apviews.signup, name='customer_signup'),
    #   url("customer/privacy_terms/accept/", gviews.accept_privacy_terms, name='customer_accept_privacy_terms'),

      # path("accounts/signup/",gviews.signup,name='account_signup'),
      url("customer/login/", apviews.customerlookup, name='customer_login'),

      # url("accounts/login/", gviews.loginuser, name='account_login'),
      # url("", gviews.loginuser, name='login'),
      url("customer/logout", apviews.logoutuser, name='customer_logout'),
    # url(r'^account_activation_sent/$', gviews.account_activation_sent,
    #     name='customer_account_activation_sent'),
    # # url(r'^accounts/', include('allauth.urls')),
    # url('activate-account', gviews.activate, name='customer_activate_account'),
    # url('createwallet', gviews.createaccounts, name='customer_create_accounts'),
    # url('resendactivationcode', gviews.resendactivationcode,
    #     name='customer_resend_activation_code'),
    # url('unsuspend', gviews.unsuspend, name='customer_unsuspend'),
    path('select_account_type/', apviews.select_account_type, name='customer_select_account_type'),
    path('confirmemail', apviews.confirmemail, name='customer_confirm_email'),
    path('confirmemailpage/', apviews.confirmemailpage, name='customer_confirm_email_page'),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

store/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import path, include, re_path
from django.contrib import admin
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static
from django.shortcuts import render, get_object_or_404
from django.views.static import serve
from django.core.exceptions import ObjectDoesNotExist
from django.core.exceptions import ValidationError

# handler500 = 'app.views.handler500'
# handler404 = 'app.views.handler404'

urlpatterns = [
    # path('admin/v2/', admin.site.urls),
        # path('admin/', admin.site.urls),
        re_path(r'',include('general.urls')),
        re_path(r'',include('app.urls')),
        re_path(r'',include('seller.urls')),
        re_path(r'',include('manager.urls')),
        re_path(r'',include('store_admin.urls')),


        # Included api_urls 
         path('api/',include('app.api_urls')),

# re_path(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}), 
# re_path(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}), 
] 
 
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)



# try:
#     admin.sites.AdminSite.site_header = gmodels.General.objects.get(pk=1).platform_name
#     admin.sites.AdminSite.site_title = 'Administration'
#     admin.sites.AdminSite.index_title = gmodels.General.objects.get(pk=1).platform_name
# except ObjectDoesNotExist:
#     admin.sites.AdminSite.site_header = admin.sites.AdminSite.site_header
#     admin.sites.AdminSite.site_title = admin.sites.AdminSite.site_title
#     admin.sites.AdminSite.index_title = admin.sites.AdminSite.index_title

seller/forms.py
from allauth.account.forms import SignupForm
from django import forms
from app import models as apmodels
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.forms import ModelForm
from seller import models as smodels

class updatecontactdetails(forms.ModelForm):
    class Meta:
        model = apmodels.Customer
        fields = ('phone_number_1','city','nearest_bus_stop','state','lga','street','street_number',)


class addproduct(forms.ModelForm):
    class Meta:
        model = apmodels.Product
        fields = ('name','image','description','price','discount','best_deal','measurement_unit','weight','available_stock')

class EditProductInformation(forms.ModelForm):
    class Meta:
        model = apmodels.Product
        fields = ('name','description','price','discount','best_deal','measurement_unit','weight','available_stock')


class addproductvariation(forms.ModelForm):
    class Meta:
        model = apmodels.ProductVariation
        fields = ('name','image','description','price','discount','measurement_unit','weight','available_stock','productid')


class addproductimage(forms.ModelForm):
    class Meta:
        model = apmodels.ProductImage
        fields = ('name','image','product')

class addsociallink(forms.ModelForm):
    class Meta:
        model = smodels.SocialLink
        fields = ('name','link','color')


class addmeasurementunit(forms.ModelForm):
    class Meta:
        model = apmodels.MeasurementUnit
        fields = ('unit',)

class EditStoreBranding(forms.ModelForm):
    class Meta:
        model = smodels.Store
        fields = ('primary_color','background_color','theme','logo', 'logo_icon',)

class EditStoreInformation(forms.ModelForm):
    class Meta:
        model = smodels.Store
        fields = ('store_name','phone_number','call_code','email', 'country','city','city_code','state','street','street_number',)

class EditStorePayment(forms.ModelForm):
    class Meta:
        model = smodels.Store
        fields = ('payment_manager','payment_processor','payment_options',)


class AddMeasurementUnit(forms.ModelForm):
    class Meta:
        model = apmodels.MeasurementUnit
        fields = ('name','unit')


class settings(forms.ModelForm):
    class Meta:
        model = smodels.Store
        fields = ('store_name','logo',)

class InitialSetup(forms.ModelForm):
    class Meta:
        model = smodels.Store
        fields = ('store_name','phone_number','call_code','email', 'country','city','city_code','state','street','street_number','logo',)

class SignUpForm(UserCreationForm):
    #gender = forms.CharField(label='First Name', widget = forms.TextInput(attrs={'class': 'form-control'}))
    email = forms.EmailField(label='Email')
    first_name = forms.CharField(label='First Name', widget = forms.TextInput(attrs={'class': 'form-control'}))
    last_name = forms.CharField(label='Last Name', widget = forms.TextInput(attrs={'class': 'form-control'}))
    # user_id = forms.CharField(widget = forms.HiddenInput(attrs={'class': 'form-control'}),required=False,)
    # user = forms.BooleanField(label='User',required=False)
    # usertype = forms.CharField(label='First Name', widget = forms.TextInput(attrs={'class': 'form-control'})

templates/custom/ahome.html
{% if request.user.is_authenticated %}
<div class="col-csxx-x-14 uk-padding-remove fixed-top" style="border-bottom-right-radius: 10px;border-bottom-left-radius: 10px;z-index: 1;position: fixed;background-color: rgb(199, 231, 231);height: 50px;opacity: 0.95;">
  <div class="card" style="position: relative;">
    <div class="uk-inline uk-position-center-right">
        <button class="uk-button uk-button-default" type="button"><i class="material-icons" style="color: gray;">notes</i></button>
        <div uk-dropdown="mode: click" class="uk-border-rounded">
            <a class="uk-link signout" style="color: black;text-decoration: none;"
                contenturl="{% url 'account_logout' %}"><i class="material-icons"
                    style="color: #7b1fa2;">exit_to_app</i> Log Out</div></a>

    </div>
  </div>
</div>    
{% endif %}

{% if request.user.is_authenticated %}
<div class="card card-nav-tabs card-plain">
  <div class="card-body" style="padding-bottom: 70px;">
    <div class="tab-content ">
      <div class="tab-pane active " id="home">
        
    {% include 'agents/home_contents.html' %}


      </div>
      <div class="tab-pane" id="transact">

      </div>
      <div class="tab-pane" id="transactions">


      </div>

      <div class="tab-pane" id="support">
     

      </div>

      
      <div class="tab-pane" id="account">
     

      </div>
    </div>
  </div>
  <div class="card-header card-header-primary fixed-bottom uk-padding-remove" style="border-radius: 0; border-top-right-radius: 10px;border-top-left-radius: 10px;height: 45px;box-shadow: none;opacity: 0.9;background:teal ;">
    <!-- colors: "header-primary", "header-info", "header-success", "header-warning", "header-danger" -->
    <div class="nav-tabs-navigation">
      <div class="nav-tabs-wrapper ">
        <ul class="nav nav-tabs uk-text-center" data-tabs="tabs" style="display: inline-block;width: 100%;margin-top: -10px;">
          <li class="nav-item col-csxx-x-2 " >
            <a class="nav-link active load-home-contents uk-padding-remove-horizontal" contenturl="{% url 'agent_home_contents' %}" data-toggle="tab" style="background-color: transparent;">
              <div style="display: inline-block; font-size: 20px; height: 30px;width: 30px;background-color:teal;border-radius: 50%;position: relative;"><i class="material-icons uk-position-center" > home</i> </div><br> Home</a>
          </li>
         
          <li class="nav-item col-csxx-x-4-e" >
            <a class="nav-link load-transactions-contents uk-padding-remove-horizontal " contenturl="{% url 'agent_transactions_contents' %}"  data-toggle="tab" style="background-color: transparent;">
              <div style="display: inline-block; font-size: 20px; height: 30px;width: 30px;background-color:teal;border-radius: 50%;position: relative;"><i class="material-icons uk-position-center" >history</i> </div><br> Transactions</a>
          </li>
<li class="nav-item col-csxx-x-3-e " >
            <a class="nav-link load-transact-contents uk-padding-remove-horizontal" contenturl="{% url 'agent_transact_contents' %}" data-toggle="tab" style="background-color: transparent;">
              <div style="display: inline-block; font-size: 20px; height: 45px;width: 45px;background-color:teal;border-radius: 50%;position: relative;"><i class="material-icons uk-position-center uk-text-lead" style="font-size: 35px;" >add_task</i></div></a>
          </li>
          <li class="nav-item col-csxx-x-3-e" >
            <a class="nav-link load-support-contents-box uk-padding-remove-horizontal"  contenturl="{% url 'agent_support_contents' %}" data-toggle="tab" style="background-color: transparent;">
              <div style="display: inline-block; font-size: 20px; height: 30px;width: 30px;background-color:teal;border-radius: 50%;position: relative;"> <i class="material-icons uk-position-center" > support</i> </div><br>Support</a>
          </li>
          <li class="nav-item col-csxx-x-3-e" >
            <a class="nav-link load-account-contents-box uk-padding-remove-horizontal"  contenturl="{% url 'agent_account_contents' %}" data-toggle="tab" style="background-color: transparent;">
              <div style="display: inline-block; font-size: 20px; height: 30px;width: 30px;background-color:teal;border-radius: 50%;position: relative;"> <i class="material-icons uk-position-center" > perm_identity</i> </div><br>Account</a>
          </li>
        </ul>
      </div>
    </div>
  </div>

</div>



<!-- Modal -->
<div id="response-modal" uk-modal>
  <div class="uk-modal-dialog uk-modal-body uk-border-rounded">
    <h2 class="uk-modal-title">Message</h2>
    <p class="modal-message"></p>
    <p class="uk-text-right">
      <button class="btn btn-primary uk-modal-close" type="button">Ok</button>

    </p>
  </div>
</div>


<div id="edit-profile-modal" uk-modal>
  <div class="uk-modal-dialog uk-modal-body uk-border-rounded">
    <h2 class="uk-modal-title">Edit Profile</h2>
    <p class="modal-message"></p>
  </div>
</div>


<div id="pin-reset-modal" uk-modal>
  <div class="uk-modal-dialog uk-modal-body uk-border-rounded">
    <h2 class="uk-modal-title">Transaction pin reset</h2>
    <p class="modal-message">Why do you want to change your Transaction Pin?</p>
    <p class="uk-text-center">
      <button class="btn btn-primary uk-padding-small uk-border-pill " id="compromised-pin-btn" contenturl="{% url 'agent_compromised_pin' %}" type="button">Compromised</button>
      <button class="btn btn-primary  uk-padding-small uk-border-pill" type="button">Forgotten</button>

    </p>
  </div>
</div>


{% endif %}

templates/custom/inline_loading_small.html
<span class=' loading uk-margin-small-right uk-position-center-right' uk-spinner='ratio: 0.5'></span>

templates/custom/interest.html
      {% for content in intereststories %}
      {% if content.content_type == 'story' %}
      <div id="{{content.story_id}}"
      class="intereststory col-cmd-2-e col-cmd-l-2-h col-cmd-xl-2 col-csl-2-e col-csm-3-e col-csx-5-e col-csxx-7 col-csxx-xx-7 col-csxx-x-14 col-css-4-e uk-text-left "
      style='margin-top:0px !important;padding: 5px;height: 200px;margin-bottom: 20px;'>
    
      <div class="uk-box-shadow-small uk-padding-remove uk-text-center"
        style='height: 200px; padding-bottom:10px;border:1px solid silver;padding-bottom: 0;border-radius: 5px !important;overflow: hidden;'>
    
        <div class="card col-xs-12 uk-padding-remove uk-margin-remove {{content.story_id}}interest" style="height: 150px;">
          <script>
          
            $.fn.readerStoryContent('{{content.story_id}}interest','{{content.story_id}}','{% url "reader_story_contents" storyid=content.story_id %}')
          </script>
         
        </div>
    
        <div class=" col-csxx-xx-14" style="padding: 2px;border-radius: 0;padding: 0;">
          <div class="uk-padding-remove  col-csxx-14 col-csxx-x-14  uk-text-left" style="margin: 0px;box-sizing: border-box;">
            <div class="uk-text-center col-csxx-14 col-csxx-x-14  uk-padding-remove" style="position: relative;">
              <div class="col-csxx-5-e col-csxx-x-5-e uk-text-center uk-padding-remove"><span class="fas fa-book-open fas-c-small"></span> <span class="text-sm">
                  {{content.number_of_episodes}}</span></div>
              <div class="col-csxx-5-e col-csxx-x-5-e uk-text-center uk-padding-remove"><span class="fas fa-book-reader fas-c-small"></span> <span class="text-sm">
                  {{content.number_of_views}}</span>
              </div>
    
              <div class="col-csxx-5-e col-csxx-x-5-e uk-text-center uk-padding-remove"><span class="fas fa-heart fas-c-small"></span> <span class="text-sm">
                {{content.number_of_loves}}</span>
            </div>
    
            </div>
            <div class="col-xs-12 d-inline-block text-truncate uk-text-center uk-padding-remove-vertical dark-mode"
              style="max-width: 100%;padding: 5px;font-weight: bold;font-size: 11px;">{{content.title}}</div>
          </div>
    
        </div>
    
      </div>
    
    </div>
          {% elif content.content_type == 'adimage' %}
          <div class="col-cmd-2-e col-cmd-l-2-h col-cmd-xl-2 col-csm-3-e col-csl-2-e col-csx-5-e col-csxx-7 col-csxx-xx-7 col-csxx-x-14 col-css-4-e"
          style='margin-top:0px !important;;padding: 5px;height: 200px;margin-bottom: 20px;position: relative;'>
      
                <span class="fas fa-ad medium uk-position-top-right" style="color: white;">
                 
                </span>
              <a href="{{content.link}} ">
      
                <img class="card-img-top " src="{{content.mobile_image.url}}" alt="" style="height: 200px;"> </a>
              </div> 
      
      
        </div>
      
          {% endif %}
            {% endfor %}
      

templates/custom/intro_carousel.html
      <!--
        Home Slider
        ==================================== -->
		
		<section id="slider" style='height:70% !important;max-height: 70%;'>
			<div id="carousel-example-generic" class="carousel slide" data-ride="carousel" style='height:100%;max-height:100%'>
			
				<!-- Indicators bullet -->
				<ol class="carousel-indicators">
					<li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
					<li data-target="#carousel-example-generic" data-slide-to="1"></li>
				</ol>
				<!-- End Indicators bullet -->				
				
				<!-- Wrapper for slides -->
				<div class="carousel-inner" role="listbox"style='height:100%;max-height:100%'>
					
					<!-- single slide -->
					{% for slide in slides  %}
					<div class="item {{slide.active_state}}" style="background-image: url({{slide.image_64}});height:100%">
						<div class="carousel-caption">
							<h2 data-wow-duration="700ms" data-wow-delay="500ms" class="wow bounceInDown animated">Meet<span> Brandi</span>!</h2>
							<h3 data-wow-duration="1000ms" class="wow slideInLeft animated"><span class="color">/creative</span> one page template.</h3>
							<p data-wow-duration="1000ms" class="wow slideInRight animated">We are a team of professionals</p>
							
							<ul class="social-links text-center">
								<li><a href=""><i class="fa fa-twitter fa-lg"></i></a></li>
								<li><a href=""><i class="fa fa-facebook fa-lg"></i></a></li>
								<li><a href=""><i class="fa fa-google-plus fa-lg"></i></a></li>
								<li><a href=""><i class="fa fa-dribbble fa-lg"></i></a></li>
							</ul>

					</div>
					<!-- end single slide -->
					{% endfor %}
					
				</div>
				<!-- End Wrapper for slides -->
				
			</div>
									</div>			<div class="card-img-overlay" style="background-image: url({{slideoverlay.image_64}});height:100%;"></div>

		</section>
		
        <!--
        End Home SliderEnd
        ==================================== -->
		
        <!--
        Features
        ==================================== -->
		

templates/custom/library_right_side_third_ad.html
 <div class=" col-md-2 col-sm-3  uk-text-center hide-xs" 
 style='background-color: white;height: 80%;float: right;margin-top: 0px;'>
<!--<h4 class="display-6" class="uk-box-shadow-small"><span class="fas fa-ad"></span></h4> -->
<div class="uk-box-shadow-small uk-border-rounded" style="height: 95%;">        
          <div class="uk-align-center recent trending uk-text-center right-side-ad-cont" style=" padding: 0;margin: 0;" uk-slideshow="autoplay: true;autoplay-interval: 10000">
            <ul class="uk-slideshow-items uk-grid-small" style="height: 100% !important;text-align:center;margin: 0;padding: 0 !important;">
              {% for ad in ads %}
              <li class="col-md-12 col-sm-12 col-xs-12 " style="height: 100% !important;padding-right: 0px;padding-left: 0px;">
                <div class="col-md-12" style="height: 100% !important; padding: 0;"> 
                  <a href="{{ad.link}}"><img class="card-img" src="{{ad.desktop_image_64}}" alt="" style="border-radius: 5px;width: 95%;height: 100%;"></a>
               
                </div>
            
              </li>
              {% endfor %}
    
    
            </ul>
           
          </div>
          </div>
  </div>

templates/custom/scene.html
{% for scene in scenes %}

<div class="col-cmd-14 ">
    <div class="jumbotron uk-margin-remove uk-padding-remove" style="margin-top: 0;background-color:transparent;position: relative;">
      <div class="uk-padding-small "> 
        <em class="display-6">{{scene.scene}}</em>
      <h3 class="display-6" style='text-align:center;font-weight:bold'>{{scene.title}}</h3>
     
      <p>{{scene.content}}</p>
     
    </div>
   </div>
    </div>


    {% endfor %}

templates/custom/signup_snippet.html
<!-- Tab panes -->
{% load i18n %}
<div class="col-md-6 col-md-offset-3 col-sm-offset-2 col-sm-8" style="margin-top: 100px;">
<form role="form" class="form-horizontal" class="signup " id="signup_form" method="post"
  action="{% url 'account_signup' %}">
  {% csrf_token %}
  {% if form.errors %}
  <div class="alert alert-warning alert-dismissible fade show" role="alert">
    <strong>Ooops!</strong>
    {{form.errors}}
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
  {% endif %}

  <div class="col-md-12 content-us ">
    <div class="contact-form shadow-sm uk-border-rounded" id="contact" style="margin-top: 0;">
      <h3 class="text-uppercase uk-text-center">Sign Up</h3>


      <div class="form-group col-md-12 col-sm-12 col-xs-12">
        
          <input class="form-control" id="id_first_name" placeholder="First Name" type="text" name="first_name"
            required >
      </div>

      <div class="form-group col-md-12 col-sm-12 col-xs-12">
        
          <input class="form-control" id="id_last_name" placeholder="Last Name" type="text" name="last_name" required>
        </div>

      <div class="form-group col-md-12 col-sm-12 col-xs-12">
        
          <input class="form-control" id="id_email" placeholder="Your email adress" type="email" name="email" required>
      </div>


      <div class="form-group col-md-12 col-sm-12 col-xs-12">
        <label for="id_category">Select Gender</label>
          <select name="gender" id="id_gender" style="" class="form-control">
            <option value="male">Male</option>
            <option value="female">Female</option>
          </select>

      </div>


      <div class="form-group col-md-12 col-sm-12 col-xs-12">
        
          <input class="form-control" id="id_username" placeholder="Username" type="text" name="username" required>

      </div>


      <div class="form-group col-md-12 col-sm-12 col-xs-12">
        <label for="id_country">Select Country</label>

          <select class="form-control selectpicker countrypicker" id='id_country' name="country" data-flag="true" data-live-search="true"></select>
      </div>

      <div class="form-group col-md-12 col-sm-12 col-xs-12">
        
          <input class="form-control" placeholder="Password" type="password" name="password1"
            autocomplete="new-password" required="" id="id_password1">
      </div>

      <div class="form-group col-md-12 col-sm-12 col-xs-12">
        
          <input class="form-control" placeholder="Confirm Password" type="password" name="password2"
            autocomplete="new-password" required="" id="id_password2">
      </div>

      <div class="form-group col-md-12 col-sm-12 col-xs-12">
        
          <input class="form-control success" id="id_writer_id" placeholder="Writer id" type="hidden" name="writer_id" required>
      </div>

      <div class="form-group col-md-12 col-sm-12 col-xs-12">
        
          <input class="form-control" id="id_client_id" placeholder="client id" type="hidden" name="client_id" required>
      </div>

      <div class="row">
        <div class="col-sm-10">
          {% if redirect_field_value %}
          <input type="hidden" name="{{ redirect_field_name }}" value="{{ redirect_field_value }}" />
          {% endif %}
          <button type="submit" class="btn btn-light btn-radius btn-brd grd1">{% trans "Sign Up" %} &raquo;</button>

        </div>
      </div>
    </div>
  </div>
</form>
</div>

templates/custom/video_ad.html
<div class="col-md-4">
    <video src="https://yootheme.com/site/images/media/yootheme-pro.mp4" loop muted playsinline uk-video="autoplay: inview" controls></video>
</div>